/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsForexRouteImport } from './routes/markets.forex'
import { Route as MarketsSyntheticsRouteImport } from './routes/markets.synthetics'
import { Route as SignalsIdRouteImport } from './routes/signals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsForexRoute = MarketsForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsSyntheticsRoute = MarketsSyntheticsRouteImport.update({
  id: '/synthetics',
  path: '/synthetics',
  getParentRoute: () => MarketsRoute,
} as any)
const SignalsIdRoute = SignalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SignalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/markets': typeof MarketsRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/performance': typeof PerformanceRoute
  '/signals': typeof SignalsRouteWithChildren
  '/markets/forex': typeof MarketsForexRoute
  '/markets/synthetics': typeof MarketsSyntheticsRoute
  '/signals/$id': typeof SignalsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/matrix': typeof MatrixRoute
  '/performance': typeof PerformanceRoute
  '/signals': typeof SignalsRouteWithChildren
  '/markets/forex': typeof MarketsForexRoute
  '/markets/synthetics': typeof MarketsSyntheticsRoute
  '/signals/$id': typeof SignalsIdRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/markets': typeof MarketsRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/performance': typeof PerformanceRoute
  '/signals': typeof SignalsRouteWithChildren
  '/markets/forex': typeof MarketsForexRoute
  '/markets/synthetics': typeof MarketsSyntheticsRoute
  '/signals/$id': typeof SignalsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/markets'
    | '/matrix'
    | '/performance'
    | '/signals'
    | '/markets/forex'
    | '/markets/synthetics'
    | '/signals/$id'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/matrix'
    | '/performance'
    | '/signals'
    | '/markets/forex'
    | '/markets/synthetics'
    | '/signals/$id'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/markets'
    | '/matrix'
    | '/performance'
    | '/signals'
    | '/markets/forex'
    | '/markets/synthetics'
    | '/signals/$id'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  MatrixRoute: typeof MatrixRoute
  PerformanceRoute: typeof PerformanceRoute
  SignalsRoute: typeof SignalsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/forex': {
      id: '/markets/forex'
      path: '/forex'
      fullPath: '/markets/forex'
      preLoaderRoute: typeof MarketsForexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/synthetics': {
      id: '/markets/synthetics'
      path: '/synthetics'
      fullPath: '/markets/synthetics'
      preLoaderRoute: typeof MarketsSyntheticsRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/signals/$id': {
      id: '/signals/$id'
      path: '/$id'
      fullPath: '/signals/$id'
      preLoaderRoute: typeof SignalsIdRouteImport
      parentRoute: typeof SignalsRoute
    }
  }
}

interface MarketsRouteChildren {
  MarketsForexRoute: typeof MarketsForexRoute
  MarketsSyntheticsRoute: typeof MarketsSyntheticsRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsForexRoute: MarketsForexRoute,
  MarketsSyntheticsRoute: MarketsSyntheticsRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface SignalsRouteChildren {
  SignalsIdRoute: typeof SignalsIdRoute
}

const SignalsRouteChildren: SignalsRouteChildren = {
  SignalsIdRoute: SignalsIdRoute,
}

const SignalsRouteWithChildren =
  SignalsRoute._addFileChildren(SignalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MarketsRoute: MarketsRouteWithChildren,
  MatrixRoute: MatrixRoute,
  PerformanceRoute: PerformanceRoute,
  SignalsRoute: SignalsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
